/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LearnTrackIndexRouteImport } from './routes/learn.$track.index'
import { Route as LearnTrackSlugRouteImport } from './routes/learn.$track.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTrackIndexRoute = LearnTrackIndexRouteImport.update({
  id: '/learn/$track/',
  path: '/learn/$track/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTrackSlugRoute = LearnTrackSlugRouteImport.update({
  id: '/learn/$track/$slug',
  path: '/learn/$track/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/learn/$track/$slug': typeof LearnTrackSlugRoute
  '/learn/$track/': typeof LearnTrackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/learn/$track/$slug': typeof LearnTrackSlugRoute
  '/learn/$track': typeof LearnTrackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/learn/$track/$slug': typeof LearnTrackSlugRoute
  '/learn/$track/': typeof LearnTrackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/learn/$track/$slug' | '/learn/$track/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/learn/$track/$slug' | '/learn/$track'
  id: '__root__' | '/' | '/demo' | '/learn/$track/$slug' | '/learn/$track/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  LearnTrackSlugRoute: typeof LearnTrackSlugRoute
  LearnTrackIndexRoute: typeof LearnTrackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$track/': {
      id: '/learn/$track/'
      path: '/learn/$track'
      fullPath: '/learn/$track/'
      preLoaderRoute: typeof LearnTrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$track/$slug': {
      id: '/learn/$track/$slug'
      path: '/learn/$track/$slug'
      fullPath: '/learn/$track/$slug'
      preLoaderRoute: typeof LearnTrackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  LearnTrackSlugRoute: LearnTrackSlugRoute,
  LearnTrackIndexRoute: LearnTrackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
